### ISSUE TITLE
No module named 'Xlib' 

### ISSUE THREAD

**Issue by eatyofood** [aidygus/LinVAM#5]
python will import Xlib from my base conda enviroment but not when i run the script...

 
Traceback (most recent call last):
  File "./main.py", line 6, in <module>
    from profileeditwnd import ProfileEditWnd
  File "/home/brando/algos/AudioPython/LinVAM/profileeditwnd.py", line 7, in <module>
    from profileexecutor import *
  File "/home/brando/algos/AudioPython/LinVAM/profileexecutor.py", line 2, in <module>
    from pynput.mouse import Button, Controller
  File "/home/brando/algos/AudioPython/LinVAM/pynput/__init__.py", line 41, in <module>
    from . import mouse
  File "/home/brando/algos/AudioPython/LinVAM/pynput/mouse/__init__.py", line 48, in <module>
    from ._xorg import Button, Controller, Listener
  File "/home/brando/algos/AudioPython/LinVAM/pynput/mouse/_xorg.py", line 32, in <module>
    import Xlib.display
ModuleNotFoundError: No module named 'Xlib'

**Comment by smirgol** [comment]
Do you run LinVAM as root or without? Did you try a `pip3 install Xlib`?
